CREATE TABLE [dbo].[K1LineItem](
	[LineID] INT IDENTITY(1,1) NOT NULL,
	[LineNumber] VARCHAR(10) NULL,
	[Box] VARCHAR(20) NULL,
	[LineDescription] VARCHAR(250) NULL,
	[TaxableIncomeRule] VARCHAR(20) NULL,
	[TaxPeriodID] INT NULL,
	[Comment] VARCHAR(MAX) NULL,
	[AllocationType] VARCHAR(50) NULL,
	[Classification] VARCHAR(32) NULL,
	[DisplayOrder] INT NOT NULL,
	[LineDataType] VARCHAR(20) NULL,
	[ClientID] INT NOT NULL,
	[CreateBy] VARCHAR(50) NULL,
	[UpdateDate] DATETIME NULL,
	[IsActive] BIT NOT NULL,
	[IsGPFeeAllocated] BIT NULL,
	[IsReadOnly] BIT NULL,
	[ApplicableToStates] VARCHAR(50) NULL,
	[TaxableIncomeRuleForStates] VARCHAR(20) NULL,
	[TRC] NVARCHAR(40) NULL,
	[TCC] NVARCHAR(40) NULL,
	[MRC] NVARCHAR(40) NULL,
	[MCC] NVARCHAR(40) NULL,
	[TCCDescription] NVARCHAR(400) NULL,
	[TransactionDate] DATETIME NULL,
	[IsTransactionDate] BIT NOT NULL,
	[IsTransfersAdjusted] BIT NULL,
	[K1CategoryID] INT NULL,
	[IsVisible] BIT NULL,
	[IsM1Adjustment] BIT NULL,
	[Is16BCalc] BIT NULL,
	[Is16CCalc] BIT NULL,
	[Is16HCalc] BIT NULL,
	[BookOrdinaryIncomeRule] VARCHAR(20) NULL,
	[IncludeLookthroughData] BIT NULL,
	[AdditionalDetail1] VARCHAR(MAX) NULL,
	[AdditionalDetail2] VARCHAR(MAX) NULL,
	[AdditionalDetail3] VARCHAR(MAX) NULL,
	[MappedToPFIC] VARCHAR(20) NULL,
	[DisplayInGAAPtoTAX] INT NOT NULL,
	[isGrossOverride] BIT NULL,
	[PFICClassType] VARCHAR(20) NULL,
	[TransferBasisAdjTypeID] INT NULL,
	[IsFDAPLineClassification] BIT NULL,
	[IsTaxHoldback] BIT NULL,
	[AllocationTypeRuleId] INT NULL,
	[IsRestrictOverrideXtract] BIT NULL,
	[IsGain731a] BIT NULL,
	[SaleOrDispositionGainLoss] VARCHAR(100) NULL,
	[DefaultDispositionGainLoss] BIT NULL,
	[SystemLineDescription] VARCHAR(250) NULL,
	[SICCode] VARCHAR(20) NULL,
	[TaxTypeId] INT NULL,
	[K3AttributeTypeID] INT NULL,
	[IsK3PYLineItem] BIT NULL,
	[CapitalGainLoss] VARCHAR(50) NULL,
	[K1K3ValidationRule] INT NULL,
	[TypeK1K3VldImport] VARCHAR(50) NULL,
	[TypeK1K3VldCalc] VARCHAR(50) NULL,
	[SchK3Part2] VARCHAR(50) NULL,
	[SchK3Part3] VARCHAR(50) NULL,
	[SchK3Part4] VARCHAR(50) NULL,
	[SchK3Part9] VARCHAR(50) NULL,
	[SchK3Part10] VARCHAR(50) NULL,
	[SchK3Part13] VARCHAR(50) NULL,
	[Custom1] VARCHAR(50) NULL,
	[Custom2] VARCHAR(50) NULL,
	[Custom3] VARCHAR(50) NULL,
	[Custom4] VARCHAR(50) NULL,
	[Custom5] VARCHAR(50) NULL,
	[StandardVsCustom] VARCHAR(25) NULL,
	[ECIWithholding] VARCHAR(10) NULL,
	[ECISubTotal] VARCHAR(10) NULL,
	[IsRestrictDataFeedbyEntInvOverride] BIT NULL,
	[IsVisiblePriorYear] BIT NULL,
	[ECILineClassification] VARCHAR(500) NULL,
	[FDAPLineClassification] VARCHAR(500) NULL,
	[Gain731aPeriod] VARCHAR(100) NULL,
	[DisparityLineClassification] VARCHAR(100) NULL
)

ALTER TABLE [dbo].[K1LineItem] ADD PRIMARY KEY ([LineID])