CREATE TABLE [dbo].[AllocationRun](
	[RunID] BIGINT IDENTITY(1,1) NOT NULL,
	[RunDate] DATETIME NULL,
	[ClientID] BIGINT NOT NULL,
	[EntityID] INT NOT NULL,
	[LowerTierEntityID] INT NULL,
	[TaxPeriodID] INT NOT NULL,
	[QueueID] BIGINT NULL,
	[YearlyWorkflowID] INT NULL,
	[PartnerWorkflowID] INT NULL,
	[K1WorkflowID] INT NULL,
	[RunStatus] VARCHAR(50) NULL,
	[StatusDesc] VARCHAR(MAX) NULL,
	[SPAWorkflowID] INT NULL,
	[SidePocketWorkflowID] INT NULL,
	[PartnerTransactionID] INT NULL,
	[RunType] VARCHAR(50) NULL,
	[PhaseID] INT NULL,
	[SPA704bWorkflowID] INT NULL,
	[StackTrace] VARCHAR(MAX) NULL,
	[ForeignCurrencyRateTransactionID] INT NULL,
	[K1InternationalWorkflowID] INT NULL,
	[StateSPAWorkflowID] BIGINT NULL,
	[RunEndDate] DATETIME NULL,
	[CostWorkflowID] BIGINT NULL,
	[CARWorkflowID] BIGINT NULL,
	[DARWorkflowID] BIGINT NULL,
	[PGWorkflowID] BIGINT NULL,
	[OffsetWorkflowID] INT NULL,
	[TransferWorkflowID] INT NULL,
	[RoundingOverrideWorkflowID] INT NULL,
	[ExcessPartnerWithholdingWorkflowID] INT NULL,
	[K3ValidationStatus] VARCHAR(20) NULL,
	[StateRoundingOverrideTransactionID] INT NULL,
	[VTNRCompositePartnerCnt] INT NULL
)

ALTER TABLE [dbo].[AllocationRun] ADD PRIMARY KEY ([RunID])