CREATE TABLE [dbo].[PFICFootnoteFlowup](
	[RunID] BIGINT NOT NULL,
	[ClientID] BIGINT NOT NULL,
	[TaxPeriodID] INT NOT NULL,
	[EntityID] INT NOT NULL,
	[FlowupEntityID] INT NOT NULL,
	[SourceEntityID] INT NOT NULL,
	[PFICFootnoteID] INT NOT NULL,
	[LineID] INT NOT NULL,
	[Amount] FLOAT NULL,
	[TextValue] VARCHAR(100) NULL,
	[PK_ID] BIGINT IDENTITY(1,1) NOT NULL
)

ALTER TABLE [dbo].[PFICFootnoteFlowup] ADD PRIMARY KEY ([PK_ID])