CREATE TABLE [dbo].[Form1042SPackage](
	[Form1042SID] INT IDENTITY(1,1) NOT NULL,
	[K1PackageID] INT NOT NULL,
	[ClientID] BIGINT NOT NULL,
	[TaxPeriodID] INT NOT NULL
)

ALTER TABLE [dbo].[Form1042SPackage] ADD PRIMARY KEY ([Form1042SID])