CREATE TABLE [dbo].[MapDataRegister](
	[MapRegisterID] INT IDENTITY(1,1) NOT NULL,
	[EntityID] INT NOT NULL,
	[LineDescription] VARCHAR(MAX) NULL,
	[RegisterTypeID] INT NOT NULL,
	[SourceTypeID] INT NOT NULL,
	[MapLineID] INT NOT NULL,
	[RegisterLineID] INT NOT NULL,
	[OperationType] VARCHAR(20) NULL,
	[ClientID] INT NOT NULL,
	[TaxPeriodID] INT NULL,
	[CreateBy] VARCHAR(50) NULL,
	[UpdateDate] DATETIME NULL,
	[CategoryID] INT NULL,
	[MapLineSubType] VARCHAR(100) NULL,
	[StateID] INT NULL,
	[PeriodID] INT NULL,
	[LevelTypeID] INT NULL,
	[IsEntityLevel] INT NULL,
	[CurrencyCode] VARCHAR(10) NULL,
	[AdjustmentTypeID] INT NULL,
	[AdjustmentSourceID] INT NULL,
	[FieldSourceID] INT NULL,
	[Quarter] INT NULL,
	[TaxTreatment] VARCHAR(200) NULL,
	[Waterfall] VARCHAR(200) NULL,
	[OffsetType] VARCHAR(200) NULL,
	[TransactionDate] VARCHAR(100) NULL,
	[LineType] VARCHAR(200) NULL,
	[GainOrLoss] VARCHAR(25) NULL,
	[AllocationTypeID] INT NULL,
	[ContributionLineClassification] VARCHAR(20) NULL,
	[ForceDisplayinReports] VARCHAR(5) NULL,
	[iFormsOutputFormat] VARCHAR(20) NULL
)

ALTER TABLE [dbo].[MapDataRegister] ADD PRIMARY KEY ([MapRegisterID])